### ISSUE TITLE
Map maximum size exceeded in AwaitDetector

### ISSUE THREAD

**Issue by fumbleforce** [monti-apm/monti-apm-core#18]
Hi, I experienced a crash on my prod server due to this error. Could this be an issue with how await ids are stored, that there can be too many awaits at once?

```
Dec  5 10:14:49 ip-172-31-27-85 web[65847]: RangeError: Map maximum size exceeded
Dec  5 10:14:49 ip-172-31-27-85 web[65847]:    at Map.set (<anonymous>)
Dec  5 10:14:49 ip-172-31-27-85 web[65847]:    at AwaitDetector.init (/var/app/current/programs/server/npm/node_modules/meteor/montiapm_agent/node_modules/@monti-apm/core/src/await-detector.ts:143:22)
Dec  5 10:14:49 ip-172-31-27-85 web[65847]:    at emitInitNative (node:internal/async_hooks:202:43)
Dec  5 10:14:49 ip-172-31-27-85 web[65847]:    at emitInitScript (node:internal/async_hooks:505:3)
Dec  5 10:14:49 ip-172-31-27-85 web[65847]:    at promiseInitHook (node:internal/async_hooks:324:3)
Dec  5 10:14:49 ip-172-31-27-85 web[65847]:    at packages/mongo/mongo_driver.js:604:19
Dec  5 10:14:49 ip-172-31-27-85 web[65847]:    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Dec  5 10:14:49 ip-172-31-27-85 web[65847]:    at Object.<anonymous> (packages/quave:collection-hooks/update.js:193:24)
Dec  5 10:14:49 ip-172-31-27-85 web[65847]:    at hook.update (packages/quave:redis-oplog/lib/mongo/Mutator.js:169:22)
Dec  5 10:14:49 ip-172-31-27-85 web[65847]:    at tasksComplete (imports/core/server/methods/task_methods.ts:107:6)
Dec  5 10:14:49 ip-172-31-27-85 web[65847]:    at MethodInvocation.tasks.complete (imports/modules/game/common/game_methods.ts:61:18)
Dec  5 10:14:49 ip-172-31-27-85 web[65847]:    at Session.<anonymous> (packages/montiapm:agent/lib/hijack/wrap_session.js:77:18)
```

Hard thing to replicate. This method call and query are pretty simple, an update to a boolean.

**Comment by zodern** [comment]
Which version of montiapm:agent are you using?

**Comment by fumbleforce** [comment]
An old one. Thank you, this seems to be fixed in beta 9
